from fastapi import FastAPI, Request, Form
from fastapi.responses import HTMLResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
import os
import json
from dotenv import load_dotenv
load_dotenv()
from app.openai_client import extract_drug_entities
from app.fda_client import fetch_generic_from_fda
from openai import OpenAI

app = FastAPI()

BASE_DIR = os.path.dirname(os.path.dirname(__file__)) if os.path.dirname(__file__) else '.'

# Serve static and templates
app.mount("/static", StaticFiles(directory=os.path.join(BASE_DIR, "static")), name="static")
templates = Jinja2Templates(directory=os.path.join(BASE_DIR, "templates"))

# Load local interactions dataset once
DATA_PATH = os.path.join(BASE_DIR, "app", "drug_food_interactions.json")
with open(DATA_PATH, "r", encoding="utf-8") as f:
    DRUG_DATA = json.load(f)


def get_food_interactions(drug_name: str):
    """Return list of food interactions for a given drug name (case-insensitive, partial match)."""
    if not isinstance(drug_name, str):
        drug_name = str(drug_name) if drug_name else ""

    drug_name = drug_name.strip().lower()
    if not drug_name:
        return []

    best_match = None

    for item in DRUG_DATA:
        if isinstance(item, dict) and "name" in item:
            name = item["name"].strip().lower()
            # Exact match first
            if name == drug_name:
                return item.get("food_interactions", [])
            # Partial match (e.g. "atorvastatin calcium" → matches "atorvastatin")
            if name in drug_name or drug_name in name:
                best_match = item

    if best_match:
        return best_match.get("food_interactions", [])

    return []


@app.get("/", response_class=HTMLResponse)
async def index(request: Request):
    """Serve the homepage."""
    return templates.TemplateResponse("index.html", {"request": request})




# add this to app/openai_client.py (below extract_drug_entities)

def generate_user_answer(interactions, user_input):
    """
    interactions: list of strings from local JSON (food interaction lines)
    user_input: original user question string
    Returns a short, user-friendly answer string generated by the model.
    """
    # keep a safe default if no interactions
    if not interactions:
        return "I couldn't find food interaction information for that medicine in the database."

    # Build short prompt
    OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")
    client = OpenAI(api_key=OPENAI_API_KEY)
    interaction_summary = " ".join(interactions)
    prompt = f"""
                You are a helpful medical-assistant (informational only, non-diagnostic).
                User question: "{user_input}"
                Known food interactions for the drug: {interaction_summary}

                Write a short, clear answer to the user (1-3 sentences). Mention any foods to avoid and a brief reason if available.
                Respond only with the answer text (no JSON).
                """

    response = client.responses.create(
        model="gpt-4o-mini",
        input=prompt,
        temperature=0.3,
    )

    # extract text safely
    text_output = response.output[0].content[0].text.strip()

    return text_output




@app.post("/api/check", response_class=JSONResponse)
async def check_interaction(description: str = Form(...)):
    """Main API endpoint: analyze user description and return food interactions."""
    # 1. Extract entities via OpenAI
    entities = extract_drug_entities(description)
    brand = entities.get("brand_name", "")
    generic = entities.get("generic_name", "")

    # 2. Query FDA if brand or generic present
    fda_info = None
    try:
        fda_info = fetch_generic_from_fda(brand, generic)
    except Exception:
        fda_info = None  # continue with fallback

    exact_generic = None
    if isinstance(fda_info, dict):
        exact_generic = fda_info.get("generic_name") or generic
    else:
        exact_generic = generic

    exact_generic = exact_generic or ""

    # 3. Look up interactions from local JSON
    interactions = get_food_interactions(exact_generic)
    ai_answer = generate_user_answer(interactions, description)

    # 5. Prepare JSON response (structured + friendly text)
    response = {
        "brand_name": brand,
        "generic_name": exact_generic,
        "interactions": interactions,
        "answer": ai_answer
    }


    return JSONResponse(content=response)
